name: "Agentic Audits"
description: "A professional framework for running automated governance, audits, and refactoring missions using AI agents."
branding:
  icon: "crosshair"
  color: "blue"

inputs:
  mission:
    description: "The agent mission prompt to execute. Required if 'template' is not provided."
    required: false
    default: ""
  template:
    description: "Name of a template file in .github/templates/ (without extension). Mutually exclusive with 'mission'."
    required: false
    default: ""
  context_files:
    description: "File paths or globs for the agent to consider."
    required: false
    default: "."
  github_token:
    description: "GitHub token with Copilot access for authentication."
    required: true
  model:
    description: "Primary Copilot model to use (e.g. gpt-4o, claude-sonnet-4). Leave blank for default."
    required: false
    default: ""
  fallback_model:
    description: "Fallback model if the primary model hits a quota or availability error."
    required: false
    default: ""
  sources_config:
    description: "Path to a YAML file defining documentation sources (MCP servers, web URLs). If the file doesn't exist, no sources are configured."
    required: false
    default: ".github/sources.yml"
  dry_run:
    description: "If true, skips PR creation."
    required: false
    default: "false"
  pr_title:
    description: "Title for the Pull Request. If not provided, the agent will generate one."
    required: false
    default: ""
  pr_body:
    description: "Body content for the Pull Request. If not provided, the agent will generate one."
    required: false
    default: ""
  pr_branch:
    description: "Branch name for the Pull Request. If not provided, you should generate a relevant one."
    required: false
    default: ""
  pr_base:
    description: "Base branch for the Pull Request."
    required: false
    default: "main"
  pr_labels:
    description: "Labels to add to the Pull Request."
    required: false
    default: "automated-pr"

runs:
  using: "composite"
  steps:
    # ── 1. Install Node.js ──────────────────────────────────────────────
    - name: Set up Node.js
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
      with:
        node-version: "24"

    # ── 2. Install gh CLI ───────────────────────────────────────────────
    - name: Install GitHub CLI
      shell: bash
      run: ${{ github.action_path }}/src/install_gh.sh

    # ── 3. Authenticate gh CLI ──────────────────────────────────────────
    - name: Configure GitHub CLI Auth
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: ${{ github.action_path }}/src/configure_gh_auth.sh

    # ── 4. Install gh-copilot extension ─────────────────────────────────
    - name: Install gh-copilot extension
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: ${{ github.action_path }}/src/install_gh_copilot.sh

    # ── 5. Load sources config, install MCP servers & configure ─────────
    - name: Load sources and configure Copilot MCP
      shell: bash
      env:
        SOURCES_CONFIG: ${{ inputs.sources_config }}
      run: ${{ github.action_path }}/src/configure_sources.sh

    # ── 6. Resolve Mission (Template or Input) ──────────────────────────
    - name: Resolve Mission
      shell: bash
      env:
        INPUT_MISSION: ${{ inputs.mission }}
        INPUT_TEMPLATE: ${{ inputs.template }}
      run: ${{ github.action_path }}/src/resolve_mission.sh

    # ── 7. Run the agent mission (with model fallback) ──────────────────
    - name: Execute agent mission
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        COPILOT_GITHUB_TOKEN: ${{ inputs.github_token }}
        CONTEXT_FILES: ${{ inputs.context_files }}
        MODEL: ${{ inputs.model }}
        FALLBACK_MODEL: ${{ inputs.fallback_model }}
        DRY_RUN: ${{ inputs.dry_run }}
        PR_BASE: ${{ inputs.pr_base }}
        PR_BRANCH: ${{ inputs.pr_branch }}
        PR_TITLE: ${{ inputs.pr_title }}
        PR_BODY: ${{ inputs.pr_body }}
        PR_LABELS: ${{ inputs.pr_labels }}
      run: ${{ github.action_path }}/src/execute_mission.sh
